### ISSUE TITLE
Icon script doesn't work on windows

### ISSUE THREAD

**Issue by hhyyrylainen** [Revolutionary-Games/Thrive-Launcher#26]
The icon script uses bash style escapes which don't work on windows. At least I think that's the issue.

It needs to be fixed for windows.

Error: 
```
Invalid Parameter - /launcher-icon.png
converting failed
```

**Comment by Themayu** [comment]
The problem is actually in ImageMagick: it's reading `launcher-icon.png` as a command-line due to being written so that it can take DOS-style command options. This, combined with poor (in my opinion) command-line parsing, means that it cannot take UNIX-style paths because it reads them as command options

**Comment by Themayu** [comment]
The way to solve this is to use the platform's preferred path separator... which for some stupid reason Ruby's developers have decided is `/` *even when the engine is running on Windows* because "it works anyway".

**Comment by hhyyrylainen** [comment]
Should be fixed by https://github.com/Revolutionary-Games/Thrive-Launcher/commit/9b0601aa65267b6359f7ab9b7e16261b68acc98a
