### ISSUE TITLE
Changing the install location on Windows is broken

### ISSUE THREAD

**Issue by BSoD38** [Revolutionary-Games/Thrive-Launcher#546]
Please note that you should only report bugs in the **launcher** here. If the launcher has successfully downloaded the game and started it, all problems after that, before the game is closed, are actually problems in the game itself. Those need to be reported to: https://github.com/Revolutionary-Games/Thrive/issues

**Describe the bug**
There seems to be an issue when selecting a new install location for Thrive in the launcher (at least on Windows). By default, it is C:\Users\(username)\AppData\Roaming\Thrive-Launcher\installed, but I wanted to change it to D:\Games\Thrive Launcher\installed. When I changed it through the launcher settings, it gave me an error when I clicked Play. I also could not browse the installed files, telling me that the path did not exist.

It seems to be prepending a `file:///` to the path, which is probably what is causing the issue.

**To Reproduce**
1. On Windows, open launcher and go to settings
2. Click on Installed Versions
3. Click "Select Install Location", and choose a path somewhere on your computer
4. Click OK and then Play
5. See error

**Expected behavior**
Changing the install location works.

**Screenshots**
![image](https://github.com/Revolutionary-Games/Thrive-Launcher/assets/15630367/aa62fab9-2a22-4183-b0ea-7aa3bfc4301c)
![image](https://github.com/Revolutionary-Games/Thrive-Launcher/assets/15630367/3d45613b-5a45-4733-941e-68e802d2e4b6)
![image](https://github.com/Revolutionary-Games/Thrive-Launcher/assets/15630367/ece4e1bf-c5fb-461d-9521-29c0471a7ddd)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Launcher version 2.1.2

**Comment by hhyyrylainen** [comment]
Looks like https://github.com/Revolutionary-Games/Thrive-Launcher/issues/512 was not the last of the reports.
Taking a new look at the folder picking, I switched the code now to use the resulting `Path.LocalPath` instead of just converting the PATH to a string. I tested and for me that results in just a normal file path on Linux, Windows and Mac so I hope that'll be a fix that works for everyone. I was just in the process of making a new launcher release today so this change will be out shortly. If you could test the new launcher version ASAP to see if the problem is resolved for you as well that'd be great.

**Comment by BSoD38** [comment]
Hi! Sorry for not responding, I was very busy these days.

I just tried the launcher, and switching paths worked fine. It seemed to have trouble moving an existing installation's game files to the new path, but apart from that everything was OK.
